services:
  web:
    image: yunseok-docker.kr.ncr.ntruss.com/backend:latest
    env_file:
      - .env
    volumes:
      - db-data:/app/data
      - static-data:/app/staticfiles
      - media-data:/app/media
    ports:
      - "8000:8000"  
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static-data:/app/staticfiles
      - media-data:/app/media
    depends_on:
      - web
    restart: always

volumes:
  db-data:
  static-data:
  media-data: