# Generated by Django 5.2.4 on 2025-08-02 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MVPVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.groupinfo')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mvp_votes_received', to=settings.AUTH_USER_MODEL)),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mvp_votes_cast', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mvp_votes',
                'unique_together': {('group', 'voter', 'vote_date')},
            },
        ),
    ]
