# Generated by Django 5.2.4 on 2025-08-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=255, unique=True)),
                ('app_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='usagerecord',
            options={'ordering': []},
        ),
        migrations.RemoveField(
            model_name='usagerecord',
            name='app_name',
        ),
        migrations.RemoveField(
            model_name='usagerecord',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='usagerecord',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='usagerecord',
            name='package_name',
        ),
        migrations.RemoveField(
            model_name='usagerecord',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='usagerecord',
            name='usage_time_ms',
        ),
        migrations.RemoveField(
            model_name='usagerecord',
            name='user',
        ),
    ]
