# Generated by Django 5.2.4 on 2025-08-04 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0002_appinfo_alter_usagerecord_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usagerecord',
            name='app',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='usage.appinfo'),
        ),
        migrations.AddField(
            model_name='usagerecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='usagerecord',
            name='end_time',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='usagerecord',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usagerecord',
            name='start_time',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='usagerecord',
            name='usage_time_ms',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='usagerecord',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
